### ISSUE TITLE
Audit cron job failing due to hardcoded table prefix

### ISSUE THREAD

**Issue by ghost** [catalyst/moodle-report_apocalypse#11]
The audit task is failing in the Moodle cron job because classes/audit_manager.php contains a hardcoded mdl_ table prefix. While this is the suggested table prefix for Moodle, this prefix is not used on all installations.

Execute scheduled task: Scheduled Flash Audit (report_apocalypse\task\scheduled_flash_audit)
... started 10:35:02. Current memory use 18.2MB.
... used 2 dbqueries
... used 0.0065739154815674 seconds
Scheduled task failed: Scheduled Flash Audit (report_apocalypse\task\scheduled_flash_audit),Error reading from database
Debug info:
Table 'moodle.mdl_files' doesn't exist
SELECT DISTINCT f.contextid, c.id AS courseid, c.fullname AS coursefullname, cat.name AS category, s.name, cx.instanceid, f.component FROM mdl_files f JOIN mdl_context cx on cx$
[array (
  0 => '%.fla',
  1 => '%.flv',
  2 => '%.swf',
)]
Backtrace:
* line 1245 of /lib/dml/mysqli_native_moodle_database.php: call to moodle_database->query_end()
* line 182 of /report/apocalypse/classes/audit_manager.php: call to mysqli_native_moodle_database->get_records_sql()
* line 53 of /report/apocalypse/classes/audit_manager.php: call to report_apocalypse\audit_manager::find_module_flash_components()
* line 54 of /report/apocalypse/classes/task/scheduled_flash_audit.php: call to report_apocalypse\audit_manager::run_audit()
* line 105 of /lib/cronlib.php: call to report_apocalypse\task\scheduled_flash_audit->execute()
* line 67 of /lib/cronlib.php: call to cron_run_inner_scheduled_task()
* line 61 of /admin/cli/cron.php: call to cron_run()

Execute scheduled task: Background processing for messaging (core\task\messaging_cleanup_task)

[user@moodle apocalypse]$ grep -R "mdl_" *
classes/audit_manager.php:        $sql .= "FROM mdl_files f "
classes/audit_manager.php:          . "JOIN mdl_context cx on cx.id = f.contextid ";
classes/audit_manager.php:            $sql .= "JOIN mdl_course_modules cm on cm.id = cx.instanceid "
classes/audit_manager.php:              . "JOIN mdl_$module s on s.id = cm.instance "
classes/audit_manager.php:              . "JOIN mdl_course c on c.id = s.course ";
classes/audit_manager.php:            $sql .= "JOIN mdl_course c on c.id = cx.instanceid ";
classes/audit_manager.php:        $sql .= "JOIN mdl_course_categories cat on cat.id = c.category "

This affects version 2019022001, release 1.2.
Thanks

**Comment by danmarsden** [comment]
grrr... how did that sneak in there.... will fix that today, thanks for the report

**Comment by ak4t0sh** [comment]
Hi @danmarsden this issue seems to be blocking for users using another prefix. Could you release a new version in the plugin DB please ?

**Comment by danmarsden** [comment]
sure - done! :-)

**Comment by ak4t0sh** [comment]
Thanks Dan ! :)
