### ISSUE TITLE
course name column header displayed as "First name / Surname"

### ISSUE THREAD

**Issue by ndunand** [catalyst/moodle-report_apocalypse#3]
this seems to be due to https://github.com/catalyst/moodle-report_apocalypse/blob/master/index.php#L68

<img width="893" alt="screenshot 2018-12-05 at 12 33 15" src="https://user-images.githubusercontent.com/762972/49517949-b1b84e80-f89d-11e8-80ae-127681dfaa73.png">

**Comment by danmarsden** [comment]
I'm not quite sure how I missed that... thanks for the report and pull request!
