### ISSUE TITLE
Query / Feature request: is there a refresh button?

### ISSUE THREAD

**Issue by DR-Bi** [catalyst/moodle-report_apocalypse#6]
Hiya,

I've got it and read the report. Deleted some of the excess activities, and expected the report to update to reflect this. (First refreshed page, then used a different tab to navigate to the report page again.)
The report looks exactly the same (could be mistaken) so I'd like to request a clearer 'Refresh' or 'Update' button.

Thanks!

**Comment by danmarsden** [comment]
The report isnt cached - but deleting content may not remove it from the database immediately  - you may need to wait for the cron process that cleans up trash.

There might be a way to exclude trash files from the report though. Feel free to help us work on this and submit a pull request.

**Comment by DR-Bi** [comment]
Ah, so just leave it and wait for now. Gotcha!
And I would happily help, but I have no idea how to code. (I've tried HTML, R, Python, and C, but R and HTML are the only ones that really made any sense to me. I can half-read PHP, which I assume Moodle's plug-ins are written in, since that's what Moodle's in, but I don't know how to write it. Trying to make sense of it at all is quite frustrating. But I would help if I could.)
