### ISSUE TITLE
Breaking: Plugin Cron job fails

### ISSUE THREAD

**Issue by tomdickman** [catalyst/moodle-report_apocalypse#9]
Production usage of the `report_apocalypse` plugin has resulted in a failure of the database query resulting in reporting of the following:

`CRITICAL: Moodle task faildelay > 600 mins
TASK: Scheduled Flash Audit (report_apocalypse\task\scheduled_flash_audit) Delay: 86400
 (Checked Mar 18 21:02:07)`

Database query needs to be rectified, @tomdickman will investigate and patch

**Comment by danmarsden** [comment]
Maybe we split it up a bit - run the query for a single activity at a time, rather than one single query

**Comment by danmarsden** [comment]
- we had to run it as a single query in the original report, but there's no reason why we could split it up now.

**Comment by tomdickman** [comment]
There's no extra information in the logs, and no stack trace, so I'm doing to add a debugging statement to the `run_audit` method to provide more information.

**Comment by tomdickman** [comment]
Ok, so I finally replicated the issue, it seems to be related to the SQL query being performed, hence `Illegal mix of collations for operation 'UNION'` is being thrown when the cron job is run.

**Comment by danmarsden** [comment]
yeah - we should be able to dump a lot of that union stuff now that we don't have to build the content in a single db call and just need to populate the new table - it probably makes sense to split that out into a few calls instead of trying to do it all in a single db query.

**Comment by tomdickman** [comment]
Thanks @danmarsden, I'll work on splitting the db calls up and joining the data on the php side instead of a massive DB call and see how this goes.

**Comment by tomdickman** [comment]
Fixed and tested in postgres and sql, merged, issue now closed
